### ISSUE TITLE
Typed property DOMDocument::$documentElement must not be accessed before initialization

### ISSUE THREAD

**Issue by alecpl** [Masterminds/html5-php#220]
I'm unable to reproduce, but one of Roundcube users created a ticket for this [here](https://github.com/roundcube/roundcubemail/issues/8826).

This is with PHP 8.1.13:
```
PHP Fatal error:  Uncaught Error: Typed property DOMDocument::$documentElement must not be accessed before initialization in /var/www/roundcube/vendor/masterminds/html5/src/HTML5/Parser/DOMTreeBuilder.php:275
Stack trace:
#0 /var/www/roundcube/vendor/masterminds/html5/src/HTML5/Parser/Tokenizer.php(399): Masterminds\HTML5\Parser\DOMTreeBuilder->startTag()
#1 /var/www/roundcube/vendor/masterminds/html5/src/HTML5/Parser/Tokenizer.php(141): Masterminds\HTML5\Parser\Tokenizer->tagName()
#2 /var/www/roundcube/vendor/masterminds/html5/src/HTML5/Parser/Tokenizer.php(82): Masterminds\HTML5\Parser\Tokenizer->consumeData()
#3 /var/www/roundcube/vendor/masterminds/html5/src/HTML5.php(161): Masterminds\HTML5\Parser\Tokenizer->parse()
#4 /var/www/roundcube/vendor/masterminds/html5/src/HTML5.php(89): Masterminds\HTML5->parse()
#5 /var/www/roundcube/program/lib/Roundcube/rcube_washtml.php(698): Masterminds\HTML5->loadHTML()
```

**Comment by stof** [comment]
Should be closed as the roundcube ticket was closed saying that upgrading PHP and roundcube fixed the issue.

**Comment by mti-1** [comment]
Got the same problem on PHP8.1.18, but I can't update to PHP8.2 right now. Do you know what could cause the problem ?

**Comment by stof** [comment]
try to update to PHP 8.1.19 (the latest 8.1 version). It might be enough to fix the issue.

**Comment by stof** [comment]
@nielsdos can you link to the PHP bug (or to the PR fixing it) ?
